name: Build And Deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Lock npm version
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.0

      - name: Build
        run: |
          npm i pnpm@8 -g 
          pnpm run init
          pnpm run build:doc

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          BRANCH: gh-pages
          FOLDER: dist
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
